services:
  # Event
  nicoSWD\IfscCalendar\Domain\Event\IFSCEventSorter: ~

  # Calendar
  nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory:
    class: nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\Calendar\ICalCalendar'
      - '@nicoSWD\IfscCalendar\Infrastructure\Calendar\JsonCalendar'

  nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilder:
    class: nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilder
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory'
      - '@nicoSWD\IfscCalendar\Domain\Event\IFSCEventsFetcher'
      - '@nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess'
      - '@nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkFetcher'
      - '@nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher'
      - '@nicoSWD\IfscCalendar\Domain\Event\IFSCEventSorter'
      - '@nicoSWD\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher'

  nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess:
    class: nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2023PostProcessor'
      - '@nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2024PostProcessor'

  nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2023PostProcessor:
    class: nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2023PostProcessor
    autowire: true

  nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2024PostProcessor:
    class: nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2024PostProcessor
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient'
      - '@nicoSWD\IfscCalendar\Domain\Event\Helpers\DOMHelper'

  # Raking
  nicoSWD\IfscCalendar\Domain\Ranking\IFSCWorldRanking:
    class: nicoSWD\IfscCalendar\Domain\Ranking\IFSCWorldRanking
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\Ranking\IFSCApiWorldRankingProvider'

  # Start List
  nicoSWD\IfscCalendar\Domain\StartList\IFSCStartListGenerator:
    class: nicoSWD\IfscCalendar\Domain\StartList\IFSCStartListGenerator
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\StartList\ApiStartListProvider'
      - '@nicoSWD\IfscCalendar\Domain\Ranking\IFSCWorldRanking'

  # YouTube
  nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkFetcher:
    class: nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkFetcher
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\YouTube\YouTubeVideoProvider'

  nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher:
    class: nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher
    autowire: true

  nicoSWD\IfscVideos\Domain\YouTube\YouTubeVideoCollection:
    class: nicoSWD\IfscVideos\Domain\YouTube\YouTubeVideoCollection
    arguments:
      - '@nicoSWD\IfscVideos\Infrastructure\YouTube\YouTubeVideoProvider'

  # Season
  nicoSWD\IfscCalendar\Domain\Season\IFSCSeasonFetcher:
    class: nicoSWD\IfscCalendar\Domain\Season\IFSCSeasonFetcher
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\Event\IFSCApiEventInfoProvider'

  # Events
  nicoSWD\IfscCalendar\Domain\Event\IFSCEventsFetcher:
    class: nicoSWD\IfscCalendar\Domain\Event\IFSCEventsFetcher
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundsScraper'
      - '@nicoSWD\IfscCalendar\Domain\StartList\IFSCStartListGenerator'
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@nicoSWD\IfscCalendar\Infrastructure\Event\IFSCApiEventInfoProvider'
      - '@nicoSWD\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher'
      - '%site_event_url%'

  nicoSWD\IfscCalendar\Domain\Event\Helpers\DOMHelper: ~
  nicoSWD\IfscCalendar\Domain\Event\Helpers\Normalizer: ~

  # Round
  nicoSWD\IfscCalendar\Domain\Round\IFSCRoundsScraper:
    class: nicoSWD\IfscCalendar\Domain\Round\IFSCRoundsScraper
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient'
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@nicoSWD\IfscCalendar\Domain\Event\Helpers\DOMHelper'
      - '@nicoSWD\IfscCalendar\Domain\Event\Helpers\Normalizer'

  nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory:
    class: nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory
    autowire: true

  # Tags
  nicoSWD\IfscCalendar\Domain\Tags\IFSCTagsParser: ~
