parameters:
  ifsc_youtube_channel_id: 'UC2MGuhIaOP6YLpUx106kTQw'
  calendar_product_identifier: '-//ifsc/ical//2.0/EN'
  calendar_published_ttl: 'PT1H'
  site_event_url: 'https://calendar.ifsc.stream/view/{season}/{event_id}'

services:
  nicoSWD\IfscCalendar\Application\Command\BuildCommand:
    class: nicoSWD\IfscCalendar\Application\Command\BuildCommand
    public: true
    tags: [ console.command ]
    lazy: true
    arguments:
      - '@nicoSWD\IfscCalendar\Application\UseCase\FetchSeasons\FetchSeasonsUseCase'
      - '@nicoSWD\IfscCalendar\Application\UseCase\BuildCalendar\BuildCalendarUseCase'

  nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClientFactory:
    class: nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClientFactory
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient'
      - '@nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClientAuthenticator'

  nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClient:
    factory: '@nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClientFactory'

  nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClientAuthenticator:
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient'
      - '@nicoSWD\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher'

  Symfony\Component\EventDispatcher\EventDispatcher: ~

  nicoSWD\IfscCalendar\Infrastructure\Event\IFSCApiEventInfoProvider:
    class: nicoSWD\IfscCalendar\Infrastructure\Event\IFSCApiEventInfoProvider
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClient'

  nicoSWD\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher:
    class: nicoSWD\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher
    autowire: true

  # Calendar
  nicoSWD\IfscCalendar\Application\UseCase\BuildCalendar\BuildCalendarUseCase:
    class: nicoSWD\IfscCalendar\Application\UseCase\BuildCalendar\BuildCalendarUseCase
    autowire: true

  nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory:
    class: nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\Calendar\ICalCalendar'
      - '@nicoSWD\IfscCalendar\Infrastructure\Calendar\JsonCalendar'

  nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilder:
    class: nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilder
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarBuilderFactory'
      - '@nicoSWD\IfscCalendar\Domain\Event\IFSCEventsFetcher'
      - '@nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess'
      - '@nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkFetcher'
      - '@nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher'
      - '@nicoSWD\IfscCalendar\Domain\Event\IFSCEventSorter'
      - '@nicoSWD\IfscCalendar\Infrastructure\DomainEvent\SymfonyEventDispatcher'

  nicoSWD\IfscCalendar\Domain\Event\IFSCEventSorter: ~
  nicoSWD\IfscCalendar\Infrastructure\Calendar\JsonCalendar: ~

  nicoSWD\IfscCalendar\Infrastructure\Calendar\ICalCalendar:
    class: nicoSWD\IfscCalendar\Infrastructure\Calendar\ICalCalendar
    arguments:
      - '@Eluceo\iCal\Presentation\Factory\CalendarFactory'
      - '%calendar_product_identifier%'
      - '%calendar_published_ttl%'

  Eluceo\iCal\Presentation\Factory\CalendarFactory: ~

  nicoSWD\IfscCalendar\Infrastructure\Ranking\IFSCApiWorldRankingProvider:
    class: nicoSWD\IfscCalendar\Infrastructure\Ranking\IFSCApiWorldRankingProvider
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClient'

  nicoSWD\IfscCalendar\Domain\Ranking\IFSCWorldRanking:
    class: nicoSWD\IfscCalendar\Domain\Ranking\IFSCWorldRanking
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\Ranking\IFSCApiWorldRankingProvider'

  nicoSWD\IfscCalendar\Infrastructure\StartList\ApiStartListProvider:
    class: nicoSWD\IfscCalendar\Infrastructure\StartList\ApiStartListProvider
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\IFSC\IFSCApiClient'

  nicoSWD\IfscCalendar\Domain\StartList\IFSCStartListGenerator:
    class: nicoSWD\IfscCalendar\Domain\StartList\IFSCStartListGenerator
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\StartList\ApiStartListProvider'
      - '@nicoSWD\IfscCalendar\Domain\Ranking\IFSCWorldRanking'

  # YouTube
  nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkFetcher:
    class: nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkFetcher
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\YouTube\YouTubeVideoProvider'

  nicoSWD\IfscCalendar\Infrastructure\YouTube\YouTubeVideoProvider:
    class: nicoSWD\IfscCalendar\Infrastructure\YouTube\YouTubeVideoProvider
    arguments:
      - '@nicoSWD\IfscVideos\Domain\YouTube\YouTubeVideoCollection'

  nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher:
    class: nicoSWD\IfscCalendar\Domain\YouTube\YouTubeLinkMatcher
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Tags\IFSCTagsParser'

  # IFSC Seasons
  nicoSWD\IfscCalendar\Application\UseCase\FetchSeasons\FetchSeasonsUseCase:
    class: nicoSWD\IfscCalendar\Application\UseCase\FetchSeasons\FetchSeasonsUseCase
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Season\IFSCSeasonFetcher'

  nicoSWD\IfscCalendar\Domain\Season\IFSCSeasonFetcher:
    class: nicoSWD\IfscCalendar\Domain\Season\IFSCSeasonFetcher
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\Event\IFSCApiEventInfoProvider'

  nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess:
    class: nicoSWD\IfscCalendar\Domain\Calendar\IFSCCalendarPostProcess
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2023PostProcessor'
      - '@nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2024PostProcessor'

  nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2023PostProcessor:
    class: nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2023PostProcessor
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'

  nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2024PostProcessor:
    class: nicoSWD\IfscCalendar\Domain\Calendar\PostProcess\Season2024PostProcessor
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient'
      - '@nicoSWD\IfscCalendar\Domain\Event\Helpers\DOMHelper'

  # Events
  nicoSWD\IfscCalendar\Domain\Event\IFSCEventsFetcher:
    class: nicoSWD\IfscCalendar\Domain\Event\IFSCEventsFetcher
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundsScraper'
      - '@nicoSWD\IfscCalendar\Domain\StartList\IFSCStartListGenerator'
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@nicoSWD\IfscCalendar\Infrastructure\Event\IFSCApiEventInfoProvider'
      - '%site_event_url%'

  nicoSWD\IfscCalendar\Domain\Round\IFSCRoundsScraper:
    class: nicoSWD\IfscCalendar\Domain\Round\IFSCRoundsScraper
    arguments:
      - '@nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient'
      - '@nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory'
      - '@nicoSWD\IfscCalendar\Domain\Event\Helpers\DOMHelper'
      - '@nicoSWD\IfscCalendar\Domain\Event\Helpers\Normalizer'

  nicoSWD\IfscCalendar\Domain\Tags\IFSCTagsParser: ~
  nicoSWD\IfscCalendar\Domain\Event\Helpers\DOMHelper: ~
  nicoSWD\IfscCalendar\Domain\Event\Helpers\Normalizer: ~

  nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory:
    class: nicoSWD\IfscCalendar\Domain\Round\IFSCRoundFactory
    arguments:
      - '@nicoSWD\IfscCalendar\Domain\Tags\IFSCTagsParser'

  # HTTP Client
  nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient:
    class: nicoSWD\IfscCalendar\Infrastructure\HttpClient\HttpGuzzleClient
    arguments:
      - '@GuzzleHttp\Client'

  # Common
  GuzzleHttp\Client: ~

  nicoSWD\IfscVideos\Domain\YouTube\YouTubeVideoCollection:
    class: nicoSWD\IfscVideos\Domain\YouTube\YouTubeVideoCollection
    arguments:
      - '@nicoSWD\IfscVideos\Infrastructure\YouTube\YouTubeVideoProvider'

  nicoSWD\IfscVideos\Infrastructure\YouTube\YouTubeVideoProvider: ~