name: "Build & Push Docker image"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Build and publish a Docker image for ${{ github.repository }}"
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GH_PACKAGES_TOKEN }}
