name: Update calendar release

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  CALENDAR_FILE_ICS: "IFSC-World-Cups-and-World-Championships.ics"
  CALENDAR_FILE_JSON: "IFSC-World-Cups-and-World-Championships.json"

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate calendar files"
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/sportclimbing/ifsc-calendar:latest
          options: -v ${{ github.workspace }}:/app
          run: | 
            ifsc-calendar \ 
              --season 2024 \
              --league "World Cups and World Championships" \
              --league "Games" \
              --league "IFSC Paraclimbing" \
              --output "/app/${{ env.CALENDAR_FILE_ICS }}" \
              --format "ics,json"

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Validate calendar"
        run: php bin/validate-calendar "${{ env.CALENDAR_FILE_JSON }}"

      - name: "Check diff"
        id: check_diff
        run: |
          curl -sSL "https://calendar.ifsc.stream/?format=json&nocache=1" --output old-calendar.json
          
          if [ $(jq '.events | length' "${{ env.CALENDAR_FILE_JSON }}") -lt 9 ]; then
            echo "Too few events found in current calendar"
            exit 1
          fi
          
          php bin/calendar-diff old-calendar.json "${{ env.CALENDAR_FILE_JSON }}" > diff.md || true
          
          if [ $(wc -w < diff.md) -gt 0 ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: "Generate tag name"
        id: date
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          echo "tag_name=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "name=$(date +'%Y/%m/%d, %H:%M') Release" >> $GITHUB_OUTPUT

      - name: "Add release"
        uses: softprops/action-gh-release@v1
        if: steps.check_diff.outputs.has_changes == 'true'
        with:
          files: |
            ${{ env.CALENDAR_FILE_ICS }}
            ${{ env.CALENDAR_FILE_JSON }}
          tag_name: ${{ steps.date.outputs.tag_name }}
          name: ${{ steps.date.outputs.name }}
          body_path: diff.md

      - name: "Run latest-tag"
        if: steps.check_diff.outputs.has_changes == 'true'
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
