name: Update calendar release

on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: "Generate calendar file"
        run: |
          composer install --no-dev --optimize-autoloader 
          php app/run.php \
              --season current \
              --league "World Cups and World Championships" \
              --output "IFSC-World-Cups-and-World-Championships.ics" \
              --format "ics,json"

      - name: "Add release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            IFSC-World-Cups-and-World-Championships.ics
            IFSC-World-Cups-and-World-Championships.json
          tag_name: latest
          body: Latest calendar release
