name: Update calendar release

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  CALENDAR_FILE_ICS: "IFSC-World-Cups-and-World-Championships.ics"
  CALENDAR_FILE_JSON: "IFSC-World-Cups-and-World-Championships.json"

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: "Generate calendar files"
        run: |
          composer install --no-dev --optimize-autoloader
          php app/run.php \
              --season 2024 \
              --league "World Cups and World Championships" \
              --output "${{ env.CALENDAR_FILE_ICS }}" \
              --format "ics,json" \

      - name: "Validate calendar"
        run: php bin/validate-calendar "${{ env.CALENDAR_FILE_JSON }}"

      - name: "Check diff"
        id: check_diff
        run: |
          curl -sSL "https://calendar.ifsc.stream/?format=json&nocache=1" --output current-calendar.json
          
          if [ $(jq '.events | length' "${{ env.CALENDAR_FILE_JSON }}") -lt 80 ]; then
            echo "Too few events found in current calendar"
            exit 1
          fi
          
          diff -C 3 current-calendar.json "${{ env.CALENDAR_FILE_JSON }}" > calendar.diff || true
          
          if [ $(wc -w < calendar.diff) -gt 0 ]; then
            echo -e "Changes:\n\`\`\`diff\n$(cat calendar.diff)\n\`\`\`" > calendar.diff
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: "Generate tag name"
        id: date
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          echo "tag_name=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
          echo "name=$(date +'%Y/%m/%d, %H:%M') Release" >> $GITHUB_OUTPUT

      - name: "Add release"
        uses: softprops/action-gh-release@v1
        if: steps.check_diff.outputs.has_changes == 'true'
        with:
          files: |
            ${{ env.CALENDAR_FILE_ICS }}
            ${{ env.CALENDAR_FILE_JSON }}
          tag_name: ${{ steps.date.outputs.tag_name }}
          name: ${{ steps.date.outputs.name }}
          body_path: calendar.diff

      - name: "Run latest-tag"
        if: steps.check_diff.outputs.has_changes == 'true'
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
